apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fellowship-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fellowship
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50